language: python
matrix:
  include:
    - python: "3.6"
      env: TOX_ENV=flake8
    - python: "3.5"
      env: TOX_ENV=py35
install:
  - pip install -U tox
  - if [[ $TOX_ENV == py35 ]]; then
      pip install -U codecov;
    fi
script:
  - tox -e $TOX_ENV
after_success:
  - if [[ $TOX_ENV == py35 ]]; then
      codecov -e $TOX_ENV;
    fi
